import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "./Header.js";


export const metadata = {
  title: "BlogNow",
  description: "Generated by Ansh Vohra",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}</body>
    </html>
  );
}
